import { Resend } from "resend";

export interface ProposalData {
	projectType: string;
	description: string;
	features: string[];
	platforms: string[];
	timeline: string;
	budget: string;
	clientName: string;
	clientEmail: string;
	estimate: {
		min: number;
		max: number;
		confidence: string;
	};
}

const OWNER_EMAIL = "marcode.chavez.jr@gmail.com";

export async function POST(request: Request) {
	try {
		const body = (await request.json()) as ProposalData;
		const { clientName, clientEmail, projectType, description, features, platforms, timeline, budget, estimate } =
			body;

		if (!clientEmail || !clientName) {
			return Response.json({ error: "Client name and email are required" }, { status: 400 });
		}

		const resendApiKey = process.env.RESEND_API_KEY;
		if (!resendApiKey) {
			console.error("RESEND_API_KEY not configured");
			return Response.json(
				{ error: "Email service not configured. Please contact Marco directly at " + OWNER_EMAIL },
				{ status: 500 }
			);
		}

		const resend = new Resend(resendApiKey);

		const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #0a1628, #1e3a5f); color: #4fc3f7; padding: 30px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 24px; }
    .content { background: #f8f9fa; padding: 30px; border: 1px solid #e9ecef; }
    .section { margin-bottom: 20px; }
    .section h3 { color: #1e3a5f; margin-bottom: 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
    .section p { margin: 0; padding: 12px; background: white; border-radius: 4px; border-left: 3px solid #4fc3f7; }
    .estimate { background: #1e3a5f; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
    .estimate .amount { font-size: 28px; font-weight: bold; color: #4fc3f7; }
    .disclaimer { font-size: 12px; color: #6c757d; font-style: italic; padding: 15px; background: #fff3cd; border-radius: 4px; margin-top: 20px; }
    .footer { background: #0a1628; color: #a8d4f0; padding: 20px; border-radius: 0 0 8px 8px; text-align: center; font-size: 12px; }
    .contact-info { background: #d4edda; padding: 15px; border-radius: 4px; margin-top: 20px; }
    .contact-info strong { color: #155724; }
    ul { margin: 0; padding-left: 20px; }
    li { padding: 4px 0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚀 New Project Proposal</h1>
    <p style="margin: 10px 0 0 0; opacity: 0.8;">Submitted via marcochavez.work</p>
  </div>
  
  <div class="content">
    <div class="contact-info">
      <strong>From:</strong> ${clientName} &lt;${clientEmail}&gt;
    </div>

    <div class="section">
      <h3>Project Type</h3>
      <p>${projectType}</p>
    </div>

    <div class="section">
      <h3>Project Description</h3>
      <p>${description || "No description provided"}</p>
    </div>

    <div class="section">
      <h3>Key Features</h3>
      <p>
        <ul>
          ${features?.map((f) => `<li>${f}</li>`).join("") || "<li>Not specified</li>"}
        </ul>
      </p>
    </div>

    <div class="section">
      <h3>Target Platforms</h3>
      <p>${platforms?.join(", ") || "Not specified"}</p>
    </div>

    <div class="section">
      <h3>Timeline</h3>
      <p>${timeline || "Not specified"}</p>
    </div>

    <div class="section">
      <h3>Client's Budget Range</h3>
      <p>${budget || "Not specified"}</p>
    </div>

    <div class="estimate">
      <div style="font-size: 12px; text-transform: uppercase; letter-spacing: 1px; opacity: 0.8;">AI-Generated Estimate</div>
      <div class="amount">$${estimate.min.toLocaleString()} - $${estimate.max.toLocaleString()}</div>
      <div style="font-size: 12px; opacity: 0.7;">Confidence: ${estimate.confidence}</div>
    </div>

    <div class="disclaimer">
      ⚠️ This estimate was generated by AI based on the client's responses. It's intended as a starting point for discussion and is open to negotiation. Please review the requirements and provide a final quote.
    </div>
  </div>

  <div class="footer">
    <p>This proposal was submitted through the Project Discovery chatbot on your portfolio.</p>
    <p>Reply to ${clientEmail} to follow up with the client.</p>
  </div>
</body>
</html>
`;

		const clientEmailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #0a1628, #1e3a5f); color: #4fc3f7; padding: 30px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 24px; }
    .content { background: #f8f9fa; padding: 30px; border: 1px solid #e9ecef; }
    .section { margin-bottom: 20px; }
    .section h3 { color: #1e3a5f; margin-bottom: 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
    .section p { margin: 0; padding: 12px; background: white; border-radius: 4px; border-left: 3px solid #4fc3f7; }
    .estimate { background: #1e3a5f; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
    .estimate .amount { font-size: 28px; font-weight: bold; color: #4fc3f7; }
    .disclaimer { font-size: 12px; color: #6c757d; font-style: italic; padding: 15px; background: #fff3cd; border-radius: 4px; margin-top: 20px; }
    .footer { background: #0a1628; color: #a8d4f0; padding: 20px; border-radius: 0 0 8px 8px; text-align: center; font-size: 12px; }
    ul { margin: 0; padding-left: 20px; }
    li { padding: 4px 0; }
    .next-steps { background: #d4edda; padding: 20px; border-radius: 4px; margin-top: 20px; }
    .next-steps h3 { color: #155724; margin-top: 0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚀 Your Project Proposal</h1>
    <p style="margin: 10px 0 0 0; opacity: 0.8;">Thank you for your interest, ${clientName}!</p>
  </div>
  
  <div class="content">
    <p>Hi ${clientName},</p>
    <p>Thank you for taking the time to share your project details with me! Here's a summary of what you submitted:</p>

    <div class="section">
      <h3>Project Type</h3>
      <p>${projectType}</p>
    </div>

    <div class="section">
      <h3>Project Description</h3>
      <p>${description || "No description provided"}</p>
    </div>

    <div class="section">
      <h3>Key Features</h3>
      <p>
        <ul>
          ${features?.map((f) => `<li>${f}</li>`).join("") || "<li>Not specified</li>"}
        </ul>
      </p>
    </div>

    <div class="section">
      <h3>Target Platforms</h3>
      <p>${platforms?.join(", ") || "Not specified"}</p>
    </div>

    <div class="section">
      <h3>Your Timeline</h3>
      <p>${timeline || "Not specified"}</p>
    </div>

    <div class="estimate">
      <div style="font-size: 12px; text-transform: uppercase; letter-spacing: 1px; opacity: 0.8;">Preliminary Estimate</div>
      <div class="amount">$${estimate.min.toLocaleString()} - $${estimate.max.toLocaleString()}</div>
    </div>

    <div class="disclaimer">
      ⚠️ This is a preliminary estimate generated based on the information you provided. The final price will be confirmed after I review your requirements in detail. This estimate is open to negotiation based on scope and timeline.
    </div>

    <div class="next-steps">
      <h3>What's Next?</h3>
      <p>I'll review your project details and get back to you within 24-48 hours with:</p>
      <ul>
        <li>Any clarifying questions I might have</li>
        <li>A more detailed estimate based on the scope</li>
        <li>Potential timeline and milestones</li>
      </ul>
      <p style="margin-top: 15px;">If you have any questions in the meantime, feel free to reply to this email or book a free consultation at <a href="https://calendar.app.google/6e6e3UNCBFGmeNea6">calendar.app.google</a>.</p>
    </div>
  </div>

  <div class="footer">
    <p>Marco Chavez Jr. | Senior Full-Stack Engineer</p>
    <p><a href="https://marcochavez.work" style="color: #4fc3f7;">marcochavez.work</a></p>
  </div>
</body>
</html>
`;

		const results = await Promise.allSettled([
			resend.emails.send({
				from: "Marco Portfolio <onboarding@resend.dev>",
				to: OWNER_EMAIL,
				replyTo: clientEmail,
				subject: `New Project Proposal: ${projectType} from ${clientName}`,
				html: emailHtml,
			}),
			resend.emails.send({
				from: "Marco Chavez <onboarding@resend.dev>",
				to: clientEmail,
				replyTo: OWNER_EMAIL,
				subject: `Your Project Proposal - ${projectType}`,
				html: clientEmailHtml,
			}),
		]);

		const ownerResult = results[0];
		const clientResult = results[1];

		const successCount = results.filter((r) => r.status === "fulfilled").length;

		if (successCount === 0) {
			console.error("Both emails failed:", results);
			return Response.json({ error: "Failed to send emails. Please try again." }, { status: 500 });
		}

		return Response.json({
			success: true,
			message:
				successCount === 2
					? "Proposal sent to both you and Marco!"
					: "Proposal sent! (One email may have been delayed)",
			details: {
				ownerEmail: ownerResult.status === "fulfilled",
				clientEmail: clientResult.status === "fulfilled",
			},
		});
	} catch (error) {
		console.error("Send proposal error:", error);
		return Response.json(
			{ error: "Something went wrong. Please contact Marco directly at " + OWNER_EMAIL },
			{ status: 500 }
		);
	}
}
